name: Publish Vue-Treegrid

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
jobs:
  deploy-package:
    if: github.event.pull_request.merged == true
    name: "Deploy Package to Actions"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0
          registry-url: https://npm.pkg.github.com/
          scope: "@ks-labs"
      - run: npm i
      - run: npm run build
      - run: echo "registry=https://npm.pkg.github.com/ks-labs" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}